#!/bin/bash
# Blocks writes to build artifacts, binary files, and dependency directories.
# Used as a PreToolUse hook for Edit|Write operations.
# Exit 2 = block the action. Exit 0 = allow.

# ── JSON payload access ──────────────────────────────────────────────────
# Prefers jq; falls back to node/json-field.js so these hooks keep working on
# machines without jq instead of denying every tool call.
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

has_json_parser() {
  command -v jq >/dev/null 2>&1 || command -v node >/dev/null 2>&1
}

json_field() {  # json_field <json-payload> <dotted.path>
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$1" | jq -r ".$2 // empty" 2>/dev/null || true
  else
    printf '%s' "$1" | node "$HOOK_DIR/json-field.js" "$2" 2>/dev/null || true
  fi
}

# Fail closed only when there is no JSON parser at all.
if ! has_json_parser; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"Neither jq nor node is available; cannot parse the hook payload.\"}}"
  exit 2
fi

INPUT=$(cat)
FILE_PATH=$(json_field "$INPUT" "tool_input.file_path")

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Block dependency and build directories
case "$FILE_PATH" in
  node_modules/*|*/node_modules/*)
    REASON="Cannot write into node_modules/. Install dependencies via package manager instead." ;;
  vendor/*|*/vendor/*)
    REASON="Cannot write into vendor/. Use dependency manager instead." ;;
  dist/*|*/dist/*|build/*|*/build/*|.next/*|*/.next/*)
    REASON="Cannot write into build output directories. These are generated by the build process." ;;
  __pycache__/*|*/__pycache__/*)
    REASON="Cannot write into __pycache__/. These are generated by Python." ;;
  .venv/*|*/.venv/*|venv/*|*/venv/*)
    REASON="Cannot write into virtual environment directories." ;;
  *)
    REASON="" ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

# Block binary and archive file extensions
BASENAME=$(basename "$FILE_PATH")
case "$BASENAME" in
  *.wasm|*.so|*.dylib|*.dll|*.exe|*.o|*.a)
    REASON="Cannot write binary files. These should be compiled, not hand-written." ;;
  *.zip|*.tar|*.tar.gz|*.tar.bz2|*.tgz|*.rar|*.7z)
    REASON="Cannot write archive files." ;;
  *.mp4|*.mov|*.avi|*.mkv|*.mp3|*.wav|*.flac)
    REASON="Cannot write media files. Add these manually outside Claude Code." ;;
  *.pyc|*.pyo|*.class)
    REASON="Cannot write compiled bytecode files." ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

exit 0
